### Create Event
POST http://localhost:8080/api/events/create
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2hoaW5hYXJtZWV0QGdtYWlsLmNvbSIsImlhdCI6MTc0Mjc3MjIwNCwiZXhwIjoxNzQyODU4NjA0fQ.ae2a9Lo4cckvvBSQXECOism4Oq9QiYbI2L7sz7eiyYE
Content-Type: application/json

{
  "eventName": "Event private",
  "eventDate": "2025-04-01T18:00:00",
  "eventLocation": "Dev10 Central",
  "isPrivate": true,
  "host": {
    "userId": 1
  }

}

### Get all public events
GET http://localhost:8080/api/events/public

### get my events
GET http://localhost:8080/api/events/accepted
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2hoaW5hYXJtZWV0QGdtYWlsLmNvbSIsImlhdCI6MTc0Mjc5MzAzOCwiZXhwIjoxNzQyODc5NDM4fQ.8cwGTjvbIMIPPpVI014_eQOpG4HXEhc0oCmM3cGUOMw

### Get events by id
GET http://localhost:8080/api/events/2
