### Join public event
POST http://localhost:8080/api/invite/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWNoaGluYUBkZXYtMTAuY29tIiwiaWF0IjoxNzQyNzcxMTQxLCJleHAiOjE3NDI4NTc1NDF9.GluCr25HtmILbjYhFT5PAq2GBwWTGJRwYj9SBLBtkMg

### Invite user to private event

POST http://localhost:8080/api/invite
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2hoaW5hYXJtZWV0QGdtYWlsLmNvbSIsImlhdCI6MTc0Mjc3MjIwNCwiZXhwIjoxNzQyODU4NjA0fQ.ae2a9Lo4cckvvBSQXECOism4Oq9QiYbI2L7sz7eiyYE
Content-Type: application/json

{
  "event": {
    "eventId": 2
  },
  "user": {
    "email": "achhina@dev-10.com"
  }
}