### Join public event
POST http://localhost:8080/api/invite/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWNoaGluYUBkZXYtMTAuY29tIiwiaWF0IjoxNzQyNzcxMTQxLCJleHAiOjE3NDI4NTc1NDF9.GluCr25HtmILbjYhFT5PAq2GBwWTGJRwYj9SBLBtkMg

### Invite user to private event
POST http://localhost:8080/api/invite
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2hoaW5hYXJtZWV0QGdtYWlsLmNvbSIsImlhdCI6MTc0MjkzMjAwOCwiZXhwIjoxNzQzMDE4NDA4fQ.XokRWMh-T0hDPtwrwMMoXPhMxAaUBo4TD00yDzz5lCI
Content-Type: application/json

{
  "event": {
    "eventId": 4
  },
  "user": {
    "email": "achhina@dev-10.com"
  }
}

### Get Invites that are not accepted
GET http://localhost:8080/api/invite
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWNoaGluYUBkZXYtMTAuY29tIiwiaWF0IjoxNzQyOTI4NzgzLCJleHAiOjE3NDMwMTUxODN9.y0V4f_jQK8qGRZXTRceQBpMuemnRJrQ6jeS6a2E3zHs

### Accept invite
PUT http://localhost:8080/api/invite/3
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWNoaGluYUBkZXYtMTAuY29tIiwiaWF0IjoxNzQyODI5NjI5LCJleHAiOjE3NDI5MTYwMjl9.OoBskKGti5MxnrRyUEtDz7bxS3miFtkcQ524HeJjKtQ

### Decline invite
DELETE http://localhost:8080/api/invite/3
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoiYWNoaGluYUBkZXYtMTAuY29tIiwiaWF0IjoxNzQyODI5OTkzLCJleHAiOjE3NDI5MTYzOTN9.AsOVjsvU5uGFJcDBZ5P0LdYwJQVemVd6-PRI6D8fvPk

### Get my events
GET http://localhost:8080/api/invite/accepted
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2hoaW5hYXJtZWV0QGdtYWlsLmNvbSIsImlhdCI6MTc0Mjg3NzU5MywiZXhwIjoxNzQyOTYzOTkzfQ.k0kUdslu-gIPfXhTUlcXf7t5W9FovP1jo3xn8wPpFDE

### Get user invite
GET http://localhost:8080/api/invite/2
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoiYWNoaGluYUBkZXYtMTAuY29tIiwiaW1hZ2VVcmwiOiJodHRwczovL3BuZy5wbmd0cmVlLmNvbS9yZWNvbW1lbmQtd29ya3MvcG5nLWNsaXBhcnQvMjAyNDEyMTMvb3VybWlkL3BuZ3RyZWUtZXhwZXJpZW5jZWQtbWFsZS1tYXN0ZXItY2hlZi1sb2dvLWlsbHVzdHJhdGlvbi1wbmctaW1hZ2VfMTQwNzI3OTMucG5nIiwiaWF0IjoxNzQzMDIxNTYyLCJleHAiOjE3NDMxMDc5NjJ9.pNRnkpYyZYHSGabTSObKAgePeTi9Rv17jl1fUMq3uwI