### Get items by event id
GET http://localhost:8080/api/item/2

### Create item
POST http://localhost:8080/api/item
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2hoaW5hYXJtZWV0QGdtYWlsLmNvbSIsImlhdCI6MTc0Mjc3MTA4MSwiZXhwIjoxNzQyODU3NDgxfQ.wMDLWiZL-HsU_TIbHDo36H5MgjfQO2gkKUphNuYd0vM
Content-Type: application/json

{
  "itemName": "Mac & Cheese",
  "itemCategory": "Main Dish",
  "event": {
    "eventId": 1
  }
}

### delete item
DELETE http://localhost:8080/api/item/4
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiY2hoaW5hYXJtZWV0QGdtYWlsLmNvbSIsImlhdCI6MTc0MjY5NzQzNSwiZXhwIjoxNzQyNzgzODM1fQ.XRGFnRAvIoanZ18uFY-81GXqhRt2lQwzZ2qD8oGvT0I
