### Register User / Duplicate email
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "chhinaarmeet@gmail.com",
  "password": "Password1"
}

### Not valid email
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "chhinaarmeet",
  "password": "password"
}

### Email required
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "",
  "password": "password"
}

### Password required
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "chhinaarmeet@gmail.com",
  "password": ""
}

### Verify User

GET http://localhost:8080/api/users/verify?code=6e8c2e24-a7fe-43ef-9f3c-6153b3681e21

### Login User
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "chhinaarmeet@gmail.com",
  "password": "Password1"
}

### Register 2nd User
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "test4@mail.com",
  "password": "Password1",
  "imageUrl": "https://png.pngtree.com/recommend-works/png-clipart/20241213/ourmid/pngtree-experienced-male-master-chef-logo-illustration-png-image_14072793.png"
}

# {
#   "email": "achhina@dev-10.com",
#   "password": "Password1"
# } 

### Verify User

GET http://localhost:8080/api/users/verify?code=e8887c4c-e055-4e5e-b1ad-dc2bfcb9e8d6

### Login User
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "achhina@dev-10.com",
  "password": "Password1"
}

### Login User
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "Password1"
}

### Updated profile picture

PUT http://localhost:8080/api/users
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjMsImVtYWlsIjoidGVzdEBtYWlsLmNvbSIsImlhdCI6MTc0MzAwMTY1NywiZXhwIjoxNzQzMDg4MDU3fQ.vZY8nmTIZ4fBARwFegJRfGAlWR7R6yliWXiuOpvAk6E
Content-Type: application/json

{
  "userId": 3,
  "imageUrl": "https://st.depositphotos.com/12220922/54223/i/450/depositphotos_542236176-stock-illustration-chef-characters-okay-hand-speech.jpg"
}