### Register User / Duplicate email
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "chhinaarmeet@gmail.com",
  "password": "Password1"
}

### Not valid email
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "chhinaarmeet",
  "password": "password"
}

### Email required
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "",
  "password": "password"
}

### Password required
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "chhinaarmeet@gmail.com",
  "password": ""
}

### Verify User

GET http://localhost:8080/api/users/verify?code=6e8c2e24-a7fe-43ef-9f3c-6153b3681e21

### Login User
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "chhinaarmeet@gmail.com",
  "password": "Password1"
}

### Register 2nd User
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "email": "achhina@dev-10.com",
  "password": "Password1"
} 

### Verify User

GET http://localhost:8080/api/users/verify?code=bc9498f9-70d2-4662-84ae-b01f26c9b778

### Login User
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email": "achhina@dev-10.com",
  "password": "Password1"
}